### ISSUE TITLE
Oneko message bar removes line scrolling limit while writing messages

### ISSUE THREAD

**Issue by AZthemute** [Faf4a/snippets#1]
The Oneko CSS does some... weird stuff such as allowing message text to scroll past the message bar and off-screen if you write a message that spans many lines, as shown below.

![image](https://github.com/user-attachments/assets/114130a1-f592-4da7-9e95-ca59430ba107)

Expected behaviour: It adds a scroll bar and stops extending the message bar after a certain point.
![image](https://github.com/user-attachments/assets/5b21ddb8-cb15-4407-88c3-2cb954c93747)

It also moves the buttons a tiny bit for me, but that's very minor.

**Comment by Faf4a** [comment]
interesting ill look into it
